### ISSUE TITLE
Plugins does not work on Intellij Community Edition 

### ISSUE THREAD

**Issue by ieugen** [Tolc/IntelliJ_Jahia_plugin#34]
Hello,

I wanted to use the CND file syntax highlighting and editing support but I can't because the plugin will not start unless it has JSP support. 

JSP support is not available in intellij community edition however. 

Could you please make the functionality available in Intellij Community edition? I believe it should be possible to extract it somehow.

Thanks,

`````
18:06	Plugin Error
			Problems found loading plugins:
			Plugin "CND Language / Jahia Framework" was not loaded: required plugin "com.intellij.jsp" not installed.
			Disable CND Language / Jahia Framework
			Open plugin manager
`````

I'm using:

`````
IntelliJ IDEA 2017.1.3
Build #IC-171.4424.56, built on May 12, 2017
JRE: 1.8.0_131-8u131-b11-2-b11 amd64
JVM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 4.9.0-3-amd64
`````

**Comment by Tolc** [comment]
Hello @ieugen,
Yes I can make that happen, I'll have to make some parts of the plugin optional and active only if IntelliJ has the JSP plugin.

[This actually seems to be quite easy to achieve ](http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html), but I wasn't aware of that possibility when I started the plugin.

I'll do that as soon as I can ;)

**Comment by Tolc** [comment]
Should be working with release 1.3.2!

**Comment by ieugen** [comment]
Works great. Thanks for the fast update. You are awesome!
