### ISSUE TITLE
Resources not found in template:addResources

### ISSUE THREAD

**Issue by totohh-zz** [Tolc/IntelliJ_Jahia_plugin#52]
Hello,
The plugin doesn't recognize multiple resources in <template:addResources if it contains whitespaces.
Ex: <template:addResources type="javascript" targetTag="body" resources="vendors/jquery.js, vendors/jquery.sticky.js"/> => jquery is OK but jquery.sticky.js is KO nevertheless the file exists in the directory (src/main/resources/javascript/vendors/jquery.sticky.js).

NB: If I remove the space, it's OK.
NB: Plugin version 2.0.3

Best regards,
Thomas

**Comment by Tolc** [comment]
Hi!
Yes this is an issue I have as well.
For some reason Idea API does not like whitespaces, and I haven't found a way around that yet...
